# Generated by Django 5.1.6 on 2025-02-15 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('category', models.CharField(choices=[('3 a 5 años', '3 a 5 años'), ('11 a 14 años', '11 a 14 años'), ('objetos decorativos', 'objetos decorativos'), ('herramientas', 'herramientas'), ('6 a 12 meses', '6 a 12 meses'), ('ropa', 'ropa'), ('5 a 8 años', '5 a 8 años'), ('1 a 2 años', '1 a 2 años'), ('muebles', 'muebles'), ('0 a 6 meses', '0 a 6 meses')], max_length=45)),
                ('picture', models.ImageField(upload_to='articulos_images')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('articulo', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='jugueteria_pechan.articulo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugueteria_pechan.cliente')),
            ],
        ),
    ]
