# Generated by Django 5.1.6 on 2025-02-15 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugueteria_pechan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='category',
            field=models.CharField(choices=[('objetos decorativos', 'objetos decorativos'), ('herramientas', 'herramientas'), ('5 a 8 años', '5 a 8 años'), ('1 a 2 años', '1 a 2 años'), ('11 a 14 años', '11 a 14 años'), ('muebles', 'muebles'), ('3 a 5 años', '3 a 5 años'), ('ropa', 'ropa'), ('6 a 12 meses', '6 a 12 meses'), ('0 a 6 meses', '0 a 6 meses')], max_length=45),
        ),
        migrations.AlterField(
            model_name='compra',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jugueteria_pechan.articulo'),
        ),
    ]
